### ISSUE TITLE
Code not working with a different dimension

### ISSUE THREAD

**Issue by ankushdas** [luborliu/TraClusAlgorithm#1]
Hi,
I am trying the TraClusAlgorithm code on my data with dimension 4. After making a few bug fixes (where the default dimension of 2 was assumed), the code still doesn't work. Can you help me out with this?

**Comment by luborliu** [comment]
Have you tried the test files I provided in the src folder? Can those files work in your computer? I tested all the files in mine and they can all work well. I guess that should be just something wrong with the data format of your input..

**Comment by ankushdas** [comment]
Hi,
All the test files in the src folder work for me as well, but they all have dimension 2. I am attaching the input file I am using. The format I am using is :-
<num_of_dimensions> (4 in my case)
<num_of_trajectories>
<trajectory_id> <num_of_points> <point co-ordinates>
....
....
[inputFile.txt](https://github.com/luborliu/TraClusAlgorithm/files/44454/inputFile.txt)

**Comment by luborliu** [comment]
You are right, There was a bug in the code which causes the program cannot handle multi-dimensional data set. I just fixed it and it should work now. But I tested your data set a few times, the program cannot give me any meaningful clusters as output. So I cannot guarantee that this implementation is really the best for your domain problem.  I will close the issue if it has no more questions. Please let me know how it goes.
