### ISSUE TITLE
Not working with Lat/Lng

### ISSUE THREAD

**Issue by lbtuda** [luborliu/TraClusAlgorithm#5]
Hi,
when I give the algo positive lat/long values (city scale) it will not provide any results, I have to multiply the coordinates with 50000 to get some results that look right.
Do you know what must be changed?

The first lines of my Input file:
`2`
`310`
`0 8 50.1140929 8.6814618 50.1146149 8.68167818 50.1150859 8.68149518 50.1148239 8.68145218 50.1150339 8.68096418 50.114249 8.68099918 50.1142019 8.68042518 50.1141889 8.6804918`
`1 6 50.1072279 8.68138318 50.1072279 8.68138318 50.1071439 8.68181818 50.1072029 8.68227318 50.1071169 8.68237118 50.1074459 8.68242318`
`2 19 50.1072799 8.6824218 50.1073869 8.68236318 50.1078019 8.68218918 50.1096359 8.68201618 50.1096359 8.68201618 50.1103239 8.6822118 50.1105649 8.68230718 50.1110849 8.68165218 50.1112619 8.68086418 50.1103349 8.68361618 50.1106389 8.68488318 50.110649 8.68487118 50.1105639 8.68497318 50.1106529 8.6848718 50.1106689 8.68485218 50.1102029 8.68497918 50.1132469 8.67887418 50.11359 8.67906818 50.1140899 8.68081418`
`3 10 50.1124399 8.67760118 50.1104349 8.68227318 50.1111129 8.68125918 50.1104969 8.68483218 50.1104349 8.68424218 50.1104039 8.68534718 50.1104859 8.68548618 50.1110159 8.68478918 50.1114359 8.68461718 50.1134519 8.67932818`
`...`

regards
Lukas

**Comment by luborliu** [comment]
This is expected behavior and I don't think this is an issue.
